In [162]:
import numpy as np
import pandas as pd
from os import listdir
import reproduccion_ulutas as rp
import time

In [163]:
mypath = 'data/instances/A1_A16'
datasets = [f for f in listdir(mypath)] #dataset reading

In [164]:
POPULATION_SIZE = 100
log = False
ejecuciones = 100

path = mypath + '/'
data = path + datasets[0]

In [165]:
i = 0
historial_efficacies = []
while i < ejecuciones:    
    matrix, m, p,number_of_operations, columns, rows = rp.part_machine_incidence_matrix(data)
    antibodies = rp.generation_initial_population(p = p, m= m, population_size = POPULATION_SIZE)
    total_cells = rp.cell_identification(antibodies = antibodies)
    total_machines, total_parts = rp.decode_cells(total_cells = total_cells, rows= rows, columns = columns, p = p, log = log)
    antibody_matrices = rp.create_machine_part_matrix(matrix = matrix, 
                                                                antibodies = antibodies, 
                                                                total_machines = total_machines, 
                                                                total_parts = total_parts)
    efficacies, affinities, voids, exceptions = rp.evaluate_antibodies(antibody_matrices = antibody_matrices, 
                                                                                    total_cells = total_cells,
                                                                                    number_of_operations = number_of_operations)
    # print(np.amax(efficacies), "\t", antibodies[np.argmax(efficacies)])
    print(antibodies[np.argmax(efficacies)])
    historial_efficacies.append(np.amax(efficacies))
    i = i +1

[10  1  4  0  0  0  0  8  9  5  3  2 11  7  6 12]
[ 0  0  7  8  1  0  0  6  5  9  4  2 11 12 10  3]
[ 0  6 12  3 10  9  4 11  7  1  2  8  5  0  0  0]
[ 3 10  0 12  9  8  2  1  5  6  7 11  4  0  0  0]
[ 0  7  4 10 12  5  6  0  0  0  8  1  3  9  2 11]
[11  3  6 12  5  7  4  2 10  1  9  8  0  0  0  0]
[ 0  3 12  6  5  8 11  2  7  4  9  0  0  0  1 10]
[ 0  7 10  0  0  5  6 11  8 12  3  9  1  2  4  0]
[ 0  8  7  0  0  5  2  4  1 12 11  3 10  9  6  0]
[ 1  9  0  4 12  8 10 11  2  3  7  5  6  0  0  0]
[ 0  0  2  5  4 12  3 11 10  6  0  1  8  0  7  9]
[ 0  2 11  0  8  3  1  9  6  7 12  4  5 10  0  0]
[ 0  0  0 10  2  8  3  7  6  4 11  1 12  5  9  0]
[ 0  6  1 10  3  7  8  9  4 11  5 12  2  0  0  0]
[ 0  7  9  3  2  0 11  6  8  1 10  4  5 12  0  0]
[ 6  8  0  0  2 12  7  1  5  3 10  4  9 11  0  0]
[ 8  7  0  0  1  4  9 11 10 12  2  5  6  3  0  0]
[ 0  9  3  2  5 11 12  4 10  1  0  7  6  8  0  0]
[ 0  0  2  4  1  3  6  9 12 11 10  0  5  7  8  0]
[ 0  9 11  1  3  0  0  8  6  2  4  5 10  7 12  0]


In [166]:
np.mean(historial_efficacies)

0.4983569667262659

In [167]:
np.max(historial_efficacies)

0.6799999999999999

0.486   0.625

0.506   0.6         

In [168]:
matrix

M1  M2  M3  M4  M5
P1   1   0   0   1   0
P2   0   1   0   1   1
P3   0   1   1   1   0
P4   0   1   1   1   1
P5   1   1   1   0   1
P6   1   0   1   0   1
P7   1   0   0   0   0